kind: Deployments
apiVersioneta: apps/v1
metadata:
     name: mrdevops
spec:
 replicas: 2
 selector:
  matchLables:
   app: mrdevops
 template:
  metadata:
   lables:
    app: mrdevops
   spec: 
     containers:
      - name: mrdevops
        image: anuragjoshi01/pipeline-demo
        imagePullPolicy: Always
        ports:
        - ContainerPort: 80
